/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoAggregatorsRouteImport } from './routes/demo.aggregators'
import { Route as DemoHeadOfficeRouteImport } from './routes/demo.head-office'
import { Route as DemoPosTillRouteImport } from './routes/demo.pos-till'
import { Route as DemoSuperAdminRouteImport } from './routes/demo.super-admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAggregatorsRoute = DemoAggregatorsRouteImport.update({
  id: '/aggregators',
  path: '/aggregators',
  getParentRoute: () => DemoRoute,
} as any)
const DemoHeadOfficeRoute = DemoHeadOfficeRouteImport.update({
  id: '/head-office',
  path: '/head-office',
  getParentRoute: () => DemoRoute,
} as any)
const DemoPosTillRoute = DemoPosTillRouteImport.update({
  id: '/pos-till',
  path: '/pos-till',
  getParentRoute: () => DemoRoute,
} as any)
const DemoSuperAdminRoute = DemoSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => DemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/pricing': typeof PricingRoute
  '/demo/aggregators': typeof DemoAggregatorsRoute
  '/demo/head-office': typeof DemoHeadOfficeRoute
  '/demo/pos-till': typeof DemoPosTillRoute
  '/demo/super-admin': typeof DemoSuperAdminRoute
  '/demo/': typeof DemoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/demo/aggregators': typeof DemoAggregatorsRoute
  '/demo/head-office': typeof DemoHeadOfficeRoute
  '/demo/pos-till': typeof DemoPosTillRoute
  '/demo/super-admin': typeof DemoSuperAdminRoute
  '/demo': typeof DemoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/pricing': typeof PricingRoute
  '/demo/aggregators': typeof DemoAggregatorsRoute
  '/demo/head-office': typeof DemoHeadOfficeRoute
  '/demo/pos-till': typeof DemoPosTillRoute
  '/demo/super-admin': typeof DemoSuperAdminRoute
  '/demo/': typeof DemoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/pricing'
    | '/demo/aggregators'
    | '/demo/head-office'
    | '/demo/pos-till'
    | '/demo/super-admin'
    | '/demo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/demo/aggregators'
    | '/demo/head-office'
    | '/demo/pos-till'
    | '/demo/super-admin'
    | '/demo'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/pricing'
    | '/demo/aggregators'
    | '/demo/head-office'
    | '/demo/pos-till'
    | '/demo/super-admin'
    | '/demo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/aggregators': {
      id: '/demo/aggregators'
      path: '/aggregators'
      fullPath: '/demo/aggregators'
      preLoaderRoute: typeof DemoAggregatorsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/head-office': {
      id: '/demo/head-office'
      path: '/head-office'
      fullPath: '/demo/head-office'
      preLoaderRoute: typeof DemoHeadOfficeRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/pos-till': {
      id: '/demo/pos-till'
      path: '/pos-till'
      fullPath: '/demo/pos-till'
      preLoaderRoute: typeof DemoPosTillRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/super-admin': {
      id: '/demo/super-admin'
      path: '/super-admin'
      fullPath: '/demo/super-admin'
      preLoaderRoute: typeof DemoSuperAdminRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface DemoRouteChildren {
  DemoAggregatorsRoute: typeof DemoAggregatorsRoute
  DemoHeadOfficeRoute: typeof DemoHeadOfficeRoute
  DemoPosTillRoute: typeof DemoPosTillRoute
  DemoSuperAdminRoute: typeof DemoSuperAdminRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAggregatorsRoute: DemoAggregatorsRoute,
  DemoHeadOfficeRoute: DemoHeadOfficeRoute,
  DemoPosTillRoute: DemoPosTillRoute,
  DemoSuperAdminRoute: DemoSuperAdminRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
